// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartLib.Infrastructure.Data;

#nullable disable

namespace SmartLib.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260515174049_AddPasswordResetFields")]
    partial class AddPasswordResetFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SmartLib.Core.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Akcija")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DatumAkcije")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EntitetId")
                        .HasColumnType("int");

                    b.Property<string>("EntitetTip")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("VrijednostiNakon")
                        .HasColumnType("longtext");

                    b.Property<string>("VrijednostiPrije")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SmartLib.Core.Models.Clanarina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumIsteka")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("aktivna");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Clanarine");
                });

            modelBuilder.Entity("SmartLib.Core.Models.Kategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Opis")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Naziv")
                        .IsUnique();

                    b.ToTable("Kategorije");
                });

            modelBuilder.Entity("SmartLib.Core.Models.Knjiga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("GodinaIzdanja")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Izdavac")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("KategorijaId")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.HasIndex("KategorijaId");

                    b.ToTable("Knjige");
                });

            modelBuilder.Entity("SmartLib.Core.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("aktivan");

                    b.Property<int>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UlogaId");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumKreiranja = new DateTime(2026, 4, 25, 9, 18, 44, 0, DateTimeKind.Utc),
                            Email = "admin@smartlib.ba",
                            Ime = "Admin",
                            LozinkaHash = "R+QQe1m/6nmEN3ZEN4gXFw==:X5nJN7Js0COVp4hLI8OT/IXLK1GT8EBHa9QqNQNalh0=",
                            Prezime = "SmartLib",
                            Status = "aktivan",
                            UlogaId = 3
                        },
                        new
                        {
                            Id = 2,
                            DatumKreiranja = new DateTime(2026, 4, 25, 9, 18, 44, 0, DateTimeKind.Utc),
                            Email = "bibliotekar@smartlib.ba",
                            Ime = "Bibliotekar",
                            LozinkaHash = "R+QQe1m/6nmEN3ZEN4gXFw==:X5nJN7Js0COVp4hLI8OT/IXLK1GT8EBHa9QqNQNalh0=",
                            Prezime = "SmartLib",
                            Status = "aktivan",
                            UlogaId = 2
                        },
                        new
                        {
                            Id = 3,
                            DatumKreiranja = new DateTime(2026, 4, 25, 9, 18, 44, 0, DateTimeKind.Utc),
                            Email = "clan@smartlib.ba",
                            Ime = "Test",
                            LozinkaHash = "R+QQe1m/6nmEN3ZEN4gXFw==:X5nJN7Js0COVp4hLI8OT/IXLK1GT8EBHa9QqNQNalh0=",
                            Prezime = "Clan",
                            Status = "aktivan",
                            UlogaId = 1
                        },
                        new
                        {
                            Id = 4,
                            DatumKreiranja = new DateTime(2026, 4, 25, 20, 47, 0, 0, DateTimeKind.Utc),
                            Email = "proba@smartlib",
                            Ime = "Amila",
                            LozinkaHash = "RXc8HNFmlRF+0H6XsJGvjg==:+Fi3Qst3q84y5t6TNlJd9zltFZgqyYHErKm+CbKRTXY=",
                            Prezime = "Babic",
                            Status = "aktivan",
                            UlogaId = 1
                        },
                        new
                        {
                            Id = 5,
                            DatumKreiranja = new DateTime(2026, 4, 26, 15, 4, 48, 0, DateTimeKind.Utc),
                            Email = "imeprezime@gmail.com",
                            Ime = "Ime",
                            LozinkaHash = "eyWukOsw1/s1sYE7WkYNVg==:fdqafu1WAN62dAwt9lyR/GSSq05y9h7PaTebwSsK4Tc=",
                            Prezime = "Prezime",
                            Status = "aktivan",
                            UlogaId = 1
                        },
                        new
                        {
                            Id = 6,
                            DatumKreiranja = new DateTime(2026, 4, 26, 21, 54, 8, 0, DateTimeKind.Utc),
                            Email = "ivlajcic1@etf.unsa.ba",
                            Ime = "Imran",
                            LozinkaHash = "v1OSV7uzmOkIb4n89gxqVQ==:ghU7xePMJ4TLW/UIySZEozPekQ+BnAyfoUgUXzU3l0k=",
                            Prezime = "Vlajcic",
                            Status = "aktivan",
                            UlogaId = 1
                        });
                });

            modelBuilder.Entity("SmartLib.Core.Models.Primjerak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumNabave")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InventarniBroj")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("KnjigaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("dostupan");

                    b.HasKey("Id");

                    b.HasIndex("InventarniBroj")
                        .IsUnique();

                    b.HasIndex("KnjigaId");

                    b.ToTable("Primjerci");
                });

            modelBuilder.Entity("SmartLib.Core.Models.Rezervacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumIsteka")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DatumRezervacije")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KnjigaId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("aktivna");

                    b.HasKey("Id");

                    b.HasIndex("KnjigaId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("SmartLib.Core.Models.Uloga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Opis")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Naziv")
                        .IsUnique();

                    b.ToTable("Uloge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Član",
                            Opis = "Član biblioteke"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Bibliotekar",
                            Opis = "Bibliotečko osoblje"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Administrator",
                            Opis = "Sistem administrator"
                        });
                });

            modelBuilder.Entity("SmartLib.Core.Models.Zaduzenje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPlaniranogVracanja")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DatumStvarnogVracanja")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DatumZaduzivanja")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("PrimjerakId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("aktivno");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("PrimjerakId");

                    b.ToTable("Zaduzenja");
                });

            modelBuilder.Entity("SmartLib.Core.Models.AuditLog", b =>
                {
                    b.HasOne("SmartLib.Core.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("SmartLib.Core.Models.Clanarina", b =>
                {
                    b.HasOne("SmartLib.Core.Models.Korisnik", "Korisnik")
                        .WithMany("Clanarine")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("SmartLib.Core.Models.Knjiga", b =>
                {
                    b.HasOne("SmartLib.Core.Models.Kategorija", "Kategorija")
                        .WithMany("Knjige")
                        .HasForeignKey("KategorijaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("SmartLib.Core.Models.Korisnik", b =>
                {
                    b.HasOne("SmartLib.Core.Models.Uloga", "Uloga")
                        .WithMany("Korisnici")
                        .HasForeignKey("UlogaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("SmartLib.Core.Models.Primjerak", b =>
                {
                    b.HasOne("SmartLib.Core.Models.Knjiga", "Knjiga")
                        .WithMany("Primjerci")
                        .HasForeignKey("KnjigaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Knjiga");
                });

            modelBuilder.Entity("SmartLib.Core.Models.Rezervacija", b =>
                {
                    b.HasOne("SmartLib.Core.Models.Knjiga", "Knjiga")
                        .WithMany("Rezervacije")
                        .HasForeignKey("KnjigaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartLib.Core.Models.Korisnik", "Korisnik")
                        .WithMany("Rezervacije")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Knjiga");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("SmartLib.Core.Models.Zaduzenje", b =>
                {
                    b.HasOne("SmartLib.Core.Models.Korisnik", "Korisnik")
                        .WithMany("Zaduzenja")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartLib.Core.Models.Primjerak", "Primjerak")
                        .WithMany("Zaduzenja")
                        .HasForeignKey("PrimjerakId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Primjerak");
                });

            modelBuilder.Entity("SmartLib.Core.Models.Kategorija", b =>
                {
                    b.Navigation("Knjige");
                });

            modelBuilder.Entity("SmartLib.Core.Models.Knjiga", b =>
                {
                    b.Navigation("Primjerci");

                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("SmartLib.Core.Models.Korisnik", b =>
                {
                    b.Navigation("Clanarine");

                    b.Navigation("Rezervacije");

                    b.Navigation("Zaduzenja");
                });

            modelBuilder.Entity("SmartLib.Core.Models.Primjerak", b =>
                {
                    b.Navigation("Zaduzenja");
                });

            modelBuilder.Entity("SmartLib.Core.Models.Uloga", b =>
                {
                    b.Navigation("Korisnici");
                });
#pragma warning restore 612, 618
        }
    }
}
